In [1]:
import pandas as pd

data = pd.read_csv('C:\\Users\\zeyad-mohamed\\Documents\\HNU\\Sixth-Semester\\Projects\\DL\\Scam Detection\\Scanning-Recommendation-Project\\Data\\raw_data\\listings.csv', encoding='utf-8')

data.head()

,id,source_url,source_site,label,title,description,price_listed,phone_model,image_paths,seller_name,seller_rating
0,8c456f7a,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\8c456f7a_0.jpg,Jumia Egypt,4.6
1,be18fa32,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,8199.0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,images\trusted\be18fa32_0.jpg,Jumia Egypt,4.4
2,0ac7088c,https://www.jumia.com.eg/galaxy-a07-6.7-inch-2...,jumia_egypt,0,"Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...","Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...",9790.0,Samsung Galaxy A07,images\trusted\0ac7088c_0.jpg,Jumia Egypt,3.6
3,67cea35b,https://www.jumia.com.eg/galaxy-a07-dual-sim-4...,jumia_egypt,0,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,7599.0,Samsung Galaxy A07,images\trusted\67cea35b_0.jpg,Jumia Egypt,4.8
4,ed57d63c,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\ed57d63c_0.jpg,Jumia Egypt,4.6

In [5]:
import sys
!{sys.executable} -m pip install ftfy

Collecting ftfy
  Using cached ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: wcwidth in C:\Users\zeyad-mohamed\AppData\Roaming\Python\Python313\site-packages (from ftfy) (0.2.14)
Using cached ftfy-6.3.1-py3-none-any.whl (44 kB)
Installing collected packages: ftfy
Successfully installed ftfy-6.3.1

In [8]:
import pandas as pd
import ftfy 

cols = ['title', 'description', 'phone_model']
for col in cols:
    data[col] = data[col].apply(lambda x: ftfy.fix_text(str(x)) if pd.notna(x) else x)

data.head(164)

,id,source_url,source_site,label,title,description,price_listed,phone_model,image_paths,seller_name,seller_rating
0,8c456f7a,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\8c456f7a_0.jpg,Jumia Egypt,4.6
1,be18fa32,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,8199.0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,images\trusted\be18fa32_0.jpg,Jumia Egypt,4.4
2,0ac7088c,https://www.jumia.com.eg/galaxy-a07-6.7-inch-2...,jumia_egypt,0,"Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...","Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...",9790.0,Samsung Galaxy A07,images\trusted\0ac7088c_0.jpg,Jumia Egypt,3.6
3,67cea35b,https://www.jumia.com.eg/galaxy-a07-dual-sim-4...,jumia_egypt,0,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,7599.0,Samsung Galaxy A07,images\trusted\67cea35b_0.jpg,Jumia Egypt,4.8
4,ed57d63c,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\ed57d63c_0.jpg,Jumia Egypt,4.6
...,...,...,...,...,...,...,...,...,...,...,...
159,0230ba2f,https://www.dubizzle.com.eg/en/ad/%D8%A8%D9%86...,olx_egypt,1,بنشتري جميع انواع الايفون المستعمل بشرط وجود ا...,بنشتري جميع انواع الايفون المستعمل بشرط وجود ا...,5000.0,بنشتري جميع انواع الايفون المستعمل بشرط وجود ا...,images\scammy\0230ba2f_0.jpg,OLX Seller,NaN
160,1f470f4e,https://www.dubizzle.com.eg/en/ad/%D8%A8%D8%B6...,olx_egypt,1,بضمان محلي سنة ايفون 14 برو ماكس 256GB جديد زي...,بضمان محلي سنة ايفون 14 برو ماكس 256GB جديد زي...,46700.0,بضمان محلي سنة ايفون 14 برو ماكس 256GB جديد زي...,images\scammy\1f470f4e_0.jpg,OLX Seller,NaN
161,d22d51b4,https://www.dubizzle.com.eg/en/ad/%D8%B9%D8%B1...,olx_egypt,1,عرض وسعر مميز IPHONE 13 128 GB بطاريات تبدا من...,عرض وسعر مميز IPHONE 13 128 GB بطاريات تبدا من...,19600.0,IPHONE 13 128 GB,images\scammy\d22d51b4_0.jpg,OLX Seller,NaN
162,cf1ed80b,https://www.dubizzle.com.eg/en/ad/red-magic-10...,olx_egypt,1,Red magic 10 air,Red magic 10 air,20000.0,Red magic 10 air,images\scammy\cf1ed80b_0.jpg,OLX Seller,NaN
163,2d0357d9,https://www.dubizzle.com.eg/en/ad/iphone-17-pr...,olx_egypt,1,Iphone 17 pro max,Iphone 17 pro max,93000.0,Iphone 17 pro max,images\scammy\2d0357d9_0.jpg,OLX Seller,NaN

In [12]:
location_words = ['cairo', 'giza', 'alexandria', 'nasr city', 'mokattam', 
                  'maadi', 'marg', 'heliopolis', 'zamalek', 'shorouk', 
                  'madinaty', 'sheikh zayed', 'corniche']
mask_location = data['title'].str.lower().apply(lambda x: any(w in x for w in location_words))
data = data[~mask_location]

# 3. Drop accessories (Amazon cases, earphones, etc.)
accessory_words = ['case', 'screen protector', 'tempered glass', 'earphone',
                   'headphone', 'cable', 'charger', 'cover', 'adapter']
mask_accessory = data['title'].str.lower().apply(lambda x: any(w in x for w in accessory_words))
data = data[~mask_accessory]

# 4. Drop duplicates
data = data.drop_duplicates(subset='id')

# 5. Reset index
data = data.reset_index(drop=True)

print(f"Total rows: {len(data)}")
print(f"Trusted (0): {len(data[data['label']==0])}")
print(f"Scammy  (1): {len(data[data['label']==1])}")
data.head()

Total rows: 290
Trusted (0): 140
Scammy  (1): 150

,id,source_url,source_site,label,title,description,price_listed,phone_model,image_paths,seller_name,seller_rating
0,8c456f7a,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\8c456f7a_0.jpg,Jumia Egypt,4.6
1,be18fa32,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,8199.0,Honor X6c Dual SIM 4G Smartphone – 256GB Stora...,images\trusted\be18fa32_0.jpg,Jumia Egypt,4.4
2,0ac7088c,https://www.jumia.com.eg/galaxy-a07-6.7-inch-2...,jumia_egypt,0,"Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...","Samsung Galaxy A07 - 6.7"" inch 256GB/8GB Dual ...",9790.0,Samsung Galaxy A07,images\trusted\0ac7088c_0.jpg,Jumia Egypt,3.6
3,67cea35b,https://www.jumia.com.eg/galaxy-a07-dual-sim-4...,jumia_egypt,0,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,Samsung Galaxy A07 Dual SIM 4G 128GB/6GB Mobil...,7599.0,Samsung Galaxy A07,images\trusted\67cea35b_0.jpg,Jumia Egypt,4.8
4,ed57d63c,https://www.jumia.com.eg/honor-x6c-dual-sim-4g...,jumia_egypt,0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,7290.0,Honor X6c Dual SIM 4G Smartphone – 128GB Stora...,images\trusted\ed57d63c_0.jpg,Jumia Egypt,4.6

In [13]:
data.to_csv('C:\\Users\\zeyad-mohamed\\Documents\\HNU\\Sixth-Semester\\Projects\\DL\\Scam Detection\\Scanning-Recommendation-Project\\Data\\raw_data\\listings(Cleaned).csv', index=False, encoding='utf-8')